# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MSG.TZ
email: storyge@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  MSG.TZ
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://msgtz.github.io" # the base hostname & protocol for your site
twitter_username: storyge
github_username:  msgtz
encoding: utf-8

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-93487964-1
disqus_shortname: msgtz

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
